version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/ruby:2.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install awesome_bot
      # run tests!
      - run:
          name: run tests
          command: |
            awesome_bot README.md --skip-save-results
