version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            gem install awesome_bot
      - run:
          name: run tests
          command: |
            awesome_bot README.md --skip-save-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
