version: 2.1

executor:
  ruby_machine:
    docker:
      - image: circleci/ruby:2.3.7
      environment:
        GEM_HOME: vendor/bundle
        BUNDLE_PATH: vendor/bundle

jobs:
  checkout_code:
    executor: ruby-machine
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
  install_ruby_dependencies:
    executor: ruby_machine
    steps:
      - attach_workspace:
          at: ~/project
      - restore_cache:
          keys:
            - gems-v1-dep-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - gems-v1-dep-{{ arch }}-{{ .Branch }}
            - gems-v1-dep
      - run: gem install bundler -v 2.0.1
      - run:
          name: Which bundler?
          command: bundle -v
      - run: bundle install
      - save_cache:
          key: gems-v1-dep-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths: 
            - vendor/bundle
      - persist_to_workspace:
          root: ~/project
          paths:
            - vendor/bundle
  run_link_test:
    executor: ruby-machine
    resource_class: small
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run Links Test
          command: |
            awesome_bot README.md

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - checkout_code:
          filters:
            tags:
              only: /.*/
      - install_ruby_dependencies:
          requires:
            - checkout_code
      - run_link_test:
          requires:
            -  install_ruby_dependencies

    



